### ISSUE TITLE
Add a .dockerignore file

### ISSUE THREAD

**Issue by borenho** [borenho/nipishe#7]
The Docker COPY instruction doesn’t honour the .gitignore file. This means that whenever you call COPY . with a wildcard argument, you could be leaking unwanted files inside your Docker image.

Fortunately you can add a .dockerignore file to your code base, which works pretty much the same way the .gitignore file does. In addition to copying over the contents of your .gitignore file, you might want to include the .git/ directory as well to the list of files ignored by Docker.

**Comment by jay-jlm** [comment]
Is this still a valid issue?
Looks like one has been added in the following commit:
https://github.com/borenho/nipishe/commit/8ab8d36e15874fd458ec510a57e6780091b48996

**Comment by borenho** [comment]
You are right @jay-jlm ! This was added with the commit referenced. Thanks!
